### ISSUE TITLE
How to handle complex numbers?

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#102]
**Level 1 (good)**

Internal operations on `Complex{Dual}` and `Complex{Tracer}` should be supported, as long as there are `Real` numbers at the start and at the end.

Requires overloading conversions and promotions, not more.

**Level 2 (still debatable)**

We could decide how to initialize tracing with complex input, and read out the tracers to create a Jacobian.

**Comment by adrhill** [comment]
I think we can closes this for now, until the need for it arises.

**If you're a user and need to compute sparsity patterns through computations involving complex numbers, please open an issue!**
