### ISSUE TITLE
Shared sets and sets with shared objects

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#107]
To avoid excessive allocations in Hessian tracing, we can make a new set type holding a reference to a shared set, such that every intermediate scalar quantity shares the same pattern (as opposed to having individual patterns).

This would require:

- Overloading `trace_input` so that each index `x[i]` points to the same shared set
- Handling the empty set intelligently to avoid re-creating shared sets in operations like `similar` and `rand`
- Once #103 is merged, overloading $\times$

Note that such shared objects would also be useful to implement tape-based recursive sets

**Comment by gdalle** [comment]
From the testing perspective, we would need to add functions with dead ends to highlight the differences:

- a shared Hessian pattern will include dead ends (see Walther 2008)
- individual Hessian patterns will ignore them

**Comment by adrhill** [comment]
Added in #135.
