### ISSUE TITLE
Hessian-tracing over ForwardDiff is broken

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#13]
See this comment by @Vaibhavdixit02: https://github.com/gdalle/DifferentiationInterface.jl/pull/165#pullrequestreview-1990786549

I think that's because we don't know how to take Tracers of `Dual` numbers or something of the sort

**Comment by gdalle** [comment]
Yeah that seems like the wisest course of action. And add the appropriate tests (no idea what these are)

**Comment by adrhill** [comment]
Is this still a desired feature now that we have `HessianTracer` #20?

**Comment by gdalle** [comment]
Nope
