### ISSUE TITLE
Missing negation

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#148]
I think https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/255 shows a missing unary operator `!`.
It's not enough to solve it though, once I fix it by adding `!` to `ops_1_to_1_z` I get another error related to sparse matrix multiplication.

**Comment by adrhill** [comment]
I'm guessing we can just ignore the three-valued logic?

> `!(x)`
>
> Boolean not. Implements [three-valued logic](https://en.wikipedia.org/wiki/Three-valued_logic), returning `missing` if `x` is `missing`.

**Comment by adrhill** [comment]
The second issue you mention is being discussed in #133, so I'll have PR #150 close this one.
