### ISSUE TITLE
Return `Symmetric` Hessians by default?

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#154]
In #151, the question popped up whether `hessian_sparsity` should return a `Symmetric{Bool, SparseMatrixCSC{Bool, Int64}}` instead of the current `SparseMatrixCSC{Bool, Int64}`.

Since this can be considered a breaking change, this feature would have to wait until we have more reasons to tag a breaking `v0.7` release.

@gdalle @Vaibhavdixit02 @amontoison I would be interested in your opinions on this!

Related issue: #14

**Comment by Vaibhavdixit02** [comment]
Solvers (with recency bias of ipopt) typically only require the lower or upper triangular, and for me the breakage wouldn't be a big problem yet. Based on the results in the linked PR this gives a median ~15% improvement in the performance which seems pretty useful to me!

**Comment by amontoison** [comment]
The issue is in the coloring, we need both triangles.
But I agree that using only triangle is relevant in terms of storage and we only need one triangle for the decompression.

**Comment by adrhill** [comment]
Alright, let's keep the default `SparseMatrixCSC{Bool, Int64}` and add an option for `Symmetric` outputs via #14. 
Thanks everyone!
