### ISSUE TITLE
Add guide on how to add custom overloads

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#163]
Similar to ForwardDiff, we can't overload all methods from all packages since our dev time is limited. Instead, write a guide on how to avoid MethodErrors by writing custom overloads.
In an ideal scenario, SCT users would then upstream these as PRs.

**Comment by SouthEndMusic** [comment]
I would much appreciate this (:

As a quick fix for `DataInterpolations` I did this:

```julia
(A::AbstractInterpolation)(t::Dual) = t
```
but you probably want to update the primal value to the actual interpolation value?

**Comment by SouthEndMusic** [comment]
I only need Jacobian sparsity. I noticed that my fix is flagged as type piracy though, indicating that this should be upstreamed?
