### ISSUE TITLE
Specialize array overloads

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#192]
At the moment, [`src/overloads/arrays.jl`](https://github.com/adrhill/SparseConnectivityTracer.jl/blob/main/src/overloads/arrays.jl) contains linear algebra functions defined on `AbstractMatrix{<:Tracer}`. Unfortunately, this dispatch will most likely never be hit, because each array type (`Matrix`, `Diagonal`, `SparseMatrixCSC`, etc.) has its own implementation of things like `*` or `det`. And `f(::ConcreteMatrixType{<:Real})` will always take precedence over `f(::AbstractMatrix{<:Tracer})`.

My suggestion: only define these overloads for the basic `Array` types (`Vector` / `Matrix`). That way, we make sure that our methods are actually hit when we want them to be. And we also provide an actionable solution for people who are stuck by failing linear algebra methods: put everything inside a normal `Array` and you should be fine.

**Comment by gdalle** [comment]
Related issues which are hopeless on abstract arrays:

- #138
- #133

**Comment by adrhill** [comment]
To add injury to their limited use, array overloads require a huge amount of effort to write and test.

An alternative mentioned in #144 is to wrap all array overloads in a function that leverages meta-programming to generate methods on `XYZArray{<:AbstractTracer}`.
However, this approach is limited to single-argument function on arrays. As mentioned in #133, multi-argument functions on arrays are even more of a pain. Quoting myself:

> [Matrix multiplication] is already complex enough for simple `AbstractMatrix` and `AbstractVector`.
> 
> It requires methods for:
> 1. Matrix of tracers * Matrix of tracers
> 1. Matrix of tracers * Vector of tracers
> 1. Vector transposed of tracers * Matrix of tracers
> 1. Vector transposed of tracers * Vector of tracers
> 1. Matrix of reals * Matrix of tracers
> 1. Matrix of reals * Vector of tracers
> 1. Vector transposed of reals * Matrix of tracers
> 1. Vector transposed of reals * Vector of tracers
> 1. Matrix of tracers * Matrix of reals
> 1. Matrix of tracers * Vector of reals
> 1. Vector transposed of tracers * Matrix of reals
> 1. Vector transposed of tracers * Vector of reals

**Comment by adrhill** [comment]
> My suggestion: only define these overloads for the basic `Array` types (`Vector` / `Matrix`). 

Arguably, a codebase that has use for SCT is written in a sparse manner and will rarely use the non-sparse `Vector` and `Matrix` types. Instead, it's more likely to perform scalar operations or use types from SparseArrays.

**Comment by gdalle** [comment]
> Arguably, a codebase that has use for SCT is written in a sparse manner and will rarely use the non-sparse Vector and Matrix types. Instead, it's more likely to perform scalar operations or use types from SparseArrays.

Not true. SCT materializes the sparsity pattern of the Jacobian, but inside the code said Jacobian never needs to exist at all. Typically, the Brusselator gives rise to sparse Jacobians without ever creating a `SparseMatrixCSC`. Same for the `Conv` layer.

**Comment by gdalle** [comment]
> As mentioned in https://github.com/adrhill/SparseConnectivityTracer.jl/issues/133, multi-argument functions on arrays are even more of a pain.

Yeah we definitely don't wanna go down the ReverseDiff road of generating truckloads of methods for combinations of lists of types. It's extremely brittle and has even broken the tests of the package for a good long while https://github.com/JuliaDiff/ReverseDiff.jl/issues/242

**Comment by adrhill** [comment]
> Typically, the Brusselator gives rise to sparse Jacobians without ever creating a SparseMatrixCSC.

Sure, but the Brusselator falls into my first category of functions:
> Instead, it's more likely to perform scalar operations

And I'm not convinced `Conv` layers are a common use-case for sparsity detection. I put them in the README because they nicely demonstrate how generic our code is. 
In fact, I'm not sure the NNlib implementation of generic convolution uses `Matrix` multiplication either. I think it also falls in the category of functions using scalar operations.

**Comment by gdalle** [comment]
Sorry I had missed the "perform scalar operations" part.

**Comment by adrhill** [comment]
Closing for now, as it would require new code generation utilities, complicate testing, the need for it hasn't arisen yet.
