### ISSUE TITLE
Interoperability with dual numbers 

### ISSUE THREAD

**Issue by SouthEndMusic** [adrhill/SparseConnectivityTracer.jl#196]
I want to obtain the Jacobian sparsity of a function whose body contains a `ForwardDiff.derivative` call. This leads to this error:

```
ERROR: MethodError: *(::SparseConnectivityTracer.GradientTracer{...}, ::ForwardDiff.Dual{...}) is ambiguous.

Possible fix, define
  *(::SparseConnectivityTracer.GradientTracer, ::ForwardDiff.Dual{Ty}) where Ty
```

Does this have a quick fix?

_Edit: I worked around it, so you can close the issue if you don't find this important._

**Comment by adrhill** [comment]
Maybe we're running into the issue described here: https://docs.julialang.org/en/v1/manual/methods/#Abstract-containers-and-element-types

**Comment by adrhill** [comment]
If this is a desired feature, we should rework the function overloading utilities for 2-to-1 functions to accept an optional type argument.

Then you could add a package extension for ForwardDiff and call something like
```Julia
eval(SCT.generate_code_2_to_1(:Base, Dual, ops_1_to_1))
```

However, I'm not sure we can make this work in combination with other package extensions.

**Comment by gdalle** [comment]
Essentially the more general takeaway is that SCT doesn't play nice with other packages based on operator overloading

**Comment by gdalle** [comment]
Maybe for operations between a `Tracer` and a number we can handle things better through [promotion](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Promotion)?

**Comment by adrhill** [comment]
> Essentially the more general takeaway is that SCT doesn't play nice with other packages based on operator overloading

More generally packages implementing 2-to-1 Base functions.

> the solution was promotion. But the error wasn't a method error so idk.

I'm not sure how we would hit type promotion if the method call itself is ambiguous. 
I'll open a draft PR and see how much complexity it adds.

**Comment by adrhill** [comment]
Basic operators from Julia Base should now work with `ForwardDiff.Dual` on main.
I'll tag a release tomorrow.

**Comment by adrhill** [comment]
After thinking about it for a day, I'm starting to think #200 shouldn't be released.
With #200, `ForwardDiff.Dual` are treated just like any other `Real` number, meaning that multiplication with a global tracer basically ignores the `ForwardDiff.Dual`. However, `ForwardDiff.Dual` could in theory contain SCT's tracers, thus returning wrong, non-conservative sparsity patterns.

While this is a general issue with `Real` number wrapper types, I feel like adding a ForwardDiff extension would signal full support for `ForwardDiff.Dual`. I therefore suggest reverting the changes in #200.

**Comment by gdalle** [comment]
I agree with that, good catch.

**Comment by adrhill** [comment]
#200 has been reverted. The newly tagged `v0.6.6` release does **not** contain a ForwardDiff extension.
