### ISSUE TITLE
Let user select set-type used in tracers

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#23]
While internal use of `BitSet` for the index sets showed a large performance increase on the Brusselator example in #4, it struggles with very large input dimensionalities, as `BitSet` is [designed for use with dense integer sets](https://docs.julialang.org/en/v1/base/collections/#Base.BitSet).

For very large, very sparse index sets, `Set{UInt64}` or implementations from other packages like [SmallCollections.jl](https://github.com/matthias314/SmallCollections.jl) might be better suited.

Ideally, users could select the right set type for their task. 

CC: @gdalle, @niklasschmitz

**Comment by gdalle** [comment]
To me this is top priority
