### ISSUE TITLE
Support "Hessians" for vector-valued functions

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#29]

**Comment by gdalle** [comment]
Not very useful if no AD backends supports it?

**Comment by adrhill** [comment]
We can already do this, we just currently don't expose it to users.

**Comment by gdalle** [comment]
In SCT maybe, in DI unclear

**Comment by adrhill** [comment]
Closing this for now in favor of prioritizing the ADTypes interface.
