### ISSUE TITLE
Return both Hessian and Jacobian patterns

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#30]
I'm not sure whether this is useful (CC @gdalle), but tracing the Hessian gives us the Jacobian pattern for free.

**Comment by gdalle** [comment]
No because Hessians are for scalar-valued functions (unless we deem #29 relevant) and Jacobians for vector-valued functions

**Comment by adrhill** [comment]
> unless we deem https://github.com/adrhill/SparseConnectivityTracer.jl/issues/29 relevant

Right, this is what I had in mind

> Jacobians are are for vector-valued functions

Not necessarily. The entire field of Deep Learning is built upon computing VJPs of scalar functions.

**Comment by adrhill** [comment]
Once again, similar to #29, this is just a question of exposing an API for functionality that always exists. 
But I do agree that it is of low-priority.

**Comment by gdalle** [comment]
> Not necessarily. The entire field of Deep Learning is built upon computing VJPs of scalar functions.

Right but these are called gradients and in the vast majority of cases they're dense. Otherwise you have useless parameters in your model

**Comment by gdalle** [comment]
I think this is made obsolete by #57, in which the `HessianTracer` also contains the gradient sparsity pattern

**Comment by adrhill** [comment]
> `HessianTracer` also contains the gradient sparsity pattern

This has always been the case (previously through the dictionary keys). This issue was only about adding a `jacobian_and_hessian_pattern` interface for users.

Since this is low priority (#14 should be addressed first), let's leave it closed for now.
