### ISSUE TITLE
HessianTracer type improvements

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#40]
https://github.com/adrhill/SparseConnectivityTracer.jl/blob/83cb0b07ea4973e95a9031c9468af50e0927d679/src/tracers.jl#L119-L121

Would it be more coherent to have keys of type `eltype(S)`, since they are also indices, rather than always `UInt64`?

**Comment by adrhill** [comment]
Sounds good. :)

**Comment by gdalle** [comment]
As seen in #45, we should also

- make the `AbstractDict` subtype parametric, e.g. to use `SortedDict` in conjunction with `SortedVector`
- rename the type parameter `T` to `I` for integer wherever it still appears
- add an inner constructor that checks `eltype(S) == I`

**Comment by adrhill** [comment]
See also #51.
