### ISSUE TITLE
Add local tracers

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#56]
Currently, all tracers return conservative global sparsity patterns.
Local sparsity can be computed by propagating a primal value as well.

**Comment by gdalle** [comment]
See #57

**Comment by adrhill** [comment]
Reopening since #59 didn't add local tracers.

**Comment by gdalle** [comment]
Operators with local behavior:

- `min` and `max`: only one of the argument matters at any given point => `min(x, bigy) = x`
- `mod` and `rem`: depending on their relative sizes, one of the arguments may not matter => `mod(x, bigy) = x`
- same with a subset of https://docs.julialang.org/en/v1.10/manual/mathematical-operations/#Division-functions

**Comment by gdalle** [comment]
Once we have primal values, we will also need to add new operators, mostly those that work with `Bool`:

- `isequal`, `isless`, `isfinite`, `isinf`, `isnan`
- possibly their friends `==`, `<`, `<=` and co (check the fallback structure for those again)

**Comment by gdalle** [comment]
Oh and of course we need to add `ifelse`:

```julia
function ifelse(b::Bool, xt::GlobalTracer, yt::GlobalTracer)
    return GlobalTracer(union(xt.inputs, yt.inputs))
end

function ifelse(b::Bool, xt::LocalTracer, yt::LocalTracer)
    return ifelse(b, xt, yt)
end
```

**Comment by gdalle** [comment]
In general, we ignore behavior on sets of measure zero (like what happens to rounding exactly at an integer). But maybe exceptions for the case of 0 would make sense?

Example:

```julia
function Base.abs(xt::LocalTracer)
    if iszero(xt.value)
        return empty(xt)
    else
        return xt
    end
end
```

**Comment by gdalle** [comment]
Do we need to reintroduce local sparsity when we:

- multiply by zero
- threshold to zero

**Comment by adrhill** [comment]
The current structure of our code would make it trivial to support the zero-product property and the additive identity.

And we could generally return empty tracers if the primal computation returns zero.

> threshold to zero

What do you mean by this?

**Comment by gdalle** [comment]
> And we could generally return empty tracers if the primal computation returns zero.

I'm worried we need to be extra careful when the zeros are not fixed but variables. For instance, we don't want to return an empty tracer for
```
f(x) = x .* x
jacobian_sparsity(f, [0.0])
```
even though there is a multiplication by zero occurring in the primal computation

**Comment by adrhill** [comment]
Right, this is where analogies to AD backends are misleading, since we are not computing VJPs/JVPs.

**Comment by adrhill** [comment]
> we don't want to return an empty tracer

An argument could be made that the "global" Jacobian of `f` is `2x` and that the "local" Jacobian of `f` evaluated at `x=0` therefore is zero.

**Comment by adrhill** [comment]
In other words, the local tracer could compute 

$\mathbb{1}[\nabla \gamma] = \mathbb{1}[\partial_\alpha \varphi\vert_\alpha] \cdot \mathbb{1}[\nabla \alpha] \vee \mathbb{1}[\partial_\beta \varphi\vert_\beta] \cdot \mathbb{1}[\nabla \beta]$

instead of 

$\mathbb{1}[\nabla \gamma] = \mathbb{1}[\partial_\alpha \varphi] \cdot \mathbb{1}[\nabla \alpha] \vee \mathbb{1}[\partial_\beta \varphi] \cdot \mathbb{1}[\nabla \beta] \quad .$

**Comment by gdalle** [comment]
This is already what the theory means, no need for the $\vert_\alpha$ in addition. What you're suggesting is something else that I can't quite put my finger on

**Comment by gdalle** [comment]
What about

```julia
f(x) = x[1] * x[2]
jacobian_sparsity(f, [0.0, 1.0])
```

In the old world, we trace both inputs, and the output gets a dependency on both.

In the new world, we would only trace the second input? The first one gets an empty tracer from the start?

**Comment by adrhill** [comment]
Right, what I'm suggesting is to give an estimate of the sparsity of $J_f\vert_x$ that is as non-conservative as possible. Counter-intuitively, this could actually make the code run faster.

**Comment by gdalle** [comment]
Right but if we give every zero value an empty tracer, that boils down to saying "when the primal value is zero, every coefficient of the gradient / Hessian that involves the corresponding variable evaluates to zero at the current point". Which I am almost certain is wrong

**Comment by gdalle** [comment]
I would steer clear of "practical speedups" that are not _first_ validated by theory

**Comment by gdalle** [comment]
```julia
f(x) = exp(x[1]) * x[2]
jacobian_sparsity(f, [0.0, 1.0])
```

If we give an empty tracer to the first index, we get something wrong

**Comment by gdalle** [comment]
Essentially, even when we have zeros in our computational graph, we can't afford to forget where they come from. Zeros are only special at the end of the graph

**Comment by adrhill** [comment]
I think you're misreading my argument. You said:

> we don't want to return an empty tracer for
> 
> ```
> f(x) = x .* x
> jacobian_sparsity(f, [0.0])
> ```
> 
> even though there is a multiplication by zero occurring in the primal computation


My point is that in this case, as written explicitly above, $\mathbb{1}[\partial_\alpha \varphi\vert_\alpha] = \mathbb{1}[\partial_\beta \varphi\vert_\beta] = 0$, so an empty tracer can be returned.


In the case of 

> ```julia
> f(x) = exp(x[1]) * x[2]
> jacobian_sparsity(f, [0.0, 1.0])
> ```


$\mathbb{1}[\partial_\alpha \varphi\vert_\alpha] \neq 0$, so according to the theory, the resulting tracer isn't empty.

**Comment by gdalle** [comment]
How about for

```julia
f(x) = exp(x[1] * x[2])
jacobian_sparsity(f, [0.0, 1.0])
```

When we compute the product `x[1] * x[2]`, even though `x[1] == 0.0`, we cannot ditch the tracing for either argument, otherwise the final sparsity will be wrong

**Comment by gdalle** [comment]
Yeah that was more of an answer to your comment on Slack, which we now both agree is wrong. I think your general idea however is right, and it only requires being more precise with the derivatives of the operators $\varphi$. The question is how precise.

For instance, derivatives of `cos` are zero on all of $\mathbb{Z}\pi$, but that's pretty useless in practice cause we have a low chance of hitting those primal values.
On the other hand, the derivative of `abs2` at zero is zero, and that's one we're relatively likely to hit.

**Comment by gdalle** [comment]
And what we really don't want to screw up is operators with more than one valid derivative, aka points of nondifferentiability. For instance, `abs` is not differentiable at zero, so what each autodiff backend returns is an implementation detail. It doesn't have to be `0`, it doesn't even have to be in the subdifferential `[-1, 1]`. In that case, $\mathbb{1}[\partial \varphi]$ should only be `0` if _all acceptable derivatives of the operator are zero_, and one otherwise.

**Comment by gdalle** [comment]
> The corresponding Jacobian 

You mean gradient.

And yes, this theory would be implemented by the following functions

```julia
nonzero_der1_arg1(*, a, b) = !iszero(b)
nonzero_der1_arg2(*, a, b) = !iszero(a)
```

**Comment by gdalle** [comment]
I think we should add tests for these finer internal functions, instead of testing the classification of operators with forwarddiff

**Comment by adrhill** [comment]
> think we should add tests for these finer internal functions with ForwardDiff, instead of testing only the global classification of operators. They are very easy to screw up without realizing.

Opened #66 to track this.

**Comment by adrhill** [comment]
> Once we have primal values, we will also need to add new operators, mostly those that work with `Bool`:
> 
> * `isequal`, `isless`, `isfinite`, `isinf`, `isnan`
> * possibly their friends `==`, `<`, `<=` and co (check the fallback structure for those again)

As a friendly reminder to myself tomorrow: we should also test on @Vaibhavdixit02's matrix exponentials.
