### ISSUE TITLE
Scalar operators to support

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#74]
I think we should look at the list on https://docs.julialang.org/en/v1.12-dev/base/math/

**Comment by gdalle** [comment]
According to @ChrisRackauckaus, to transition the SciML ecosystem from Symbolics to SparseConnectivityTracer, we would need to support the equivalent of:

- [DiffRules.jl](https://github.com/JuliaDiff/DiffRules.jl)
- [NaNMath.jl](https://github.com/JuliaMath/NaNMath.jl)
- [DataInterpolations.jl](https://github.com/SciML/DataInterpolations.jl)

**Comment by adrhill** [comment]
DiffRules has a nice list of things we need to support: https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl

I guess this means adding a package extension for NaNMath and more SpecialFunctions?
Not sure what DataInterpolations requires, but some of the recently opened issues on `round` were related to it.

**Comment by adrhill** [comment]
With #178, #184 and #187, we are very close to supporting SciML.
Some methods might be missing, but adding them to the existing extensions should be trivial.
