### ISSUE TITLE
Make `AbstractTracer` a subtype of `Real`, not `Number`

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#91]
Increases compatibility with existing code

**Comment by gdalle** [comment]
Would solve https://github.com/control-toolbox/CTDirect.jl/issues/88#issuecomment-2120736903

**Comment by jbcaillau** [comment]
@gdalle thank you for feedback. well, if this indeed solves the issue, this is most welcome. given the current type hierarchy, this seems to be no problem provided that no complex numbers are involved 👀.
![IMG_3145](https://github.com/adrhill/SparseConnectivityTracer.jl/assets/62183989/90b6f7f2-6a85-4523-b3d8-862f59628dd8)

**Comment by adrhill** [comment]
Sounds reasonable. We won't touch differentiation of complex numbers anyway, so this would only have been relevant for `connectivity_pattern` on complex functions, which isn't our priority.

I'll tag a last patch release and add this breaking change.

**Comment by adrhill** [comment]
Some weirdness resulting from this: our local tracer type `Dual` can contain a `Complex` primal value but is `Real`.
Maybe the most sane fix is to constrain the primal to `Real` as well.

**Comment by gdalle** [comment]
I agree, and we'll be forever banning complex autodiff (but so did ForwardDiff)

**Comment by gdalle** [comment]
Based on the way tracers are constructed, if the function signature is `f(::Vector{<:Real})`, the primal values will never be anything but `Real` anyway

**Comment by gdalle** [comment]
Reopening until #95 is merged

**Comment by jbcaillau** [comment]
> I agree, and we'll be forever banning complex autodiff (but so did ForwardDiff)

Indeed, replacing $\varepsilon^2=-1$ by $\varepsilon^2=0$ is all about ForwardDiff.jl 🤭
